### ISSUE TITLE
Lite version

### ISSUE THREAD

**Issue by Cu8eeeR** [WhiteNeo/lastposter-avatar-mybb18x-series#3]
Hi @WhiteNeo - it would be really nice if you can release a light version of your plugin. What features should be included?

1.- Avatars in showthread.
2.- Avatars on index.
3.- Avatars on private messages.
4.- Avatars in portal.

New features:
- add title and alt tags support for all avatars
- add support to show thread contributor

Thats all, everything else is just useless if you wanna add only last post avatars to your forum. Think about it. Thank you for your work! See ya!

**Comment by WhiteNeo** [comment]
thanks for your sugestions i'll work on it.

by the way in recent version all can be enabled/disabled to make a 100%
version to all necesities :)

i know many do not use some features give a try setting up options and let
me know to work on it i will add your sugestions due is necesary for all
community

**Comment by Cu8eeeR** [comment]
@WhiteNeo - I really dont like template changes which are applied automatically during plugin installation process. It is better to add template changes manually and adjust it for own needs. It is really better than revert all unneeded changes and find what was added during installation.

As you wrote - it is all in one, do we need all these extra features? I think there are many users who just wanna use profile popup window feature; use only last post avatars etc. This plugin should be lightweighted to almost "zero" impact on performance. 

About thread contributor's avatar:
here is more info: https://github.com/tommm/flpavatar#show-thread

Titles:
Same as link above - nice addition to show more info to users, dont you think?

EDIT: Does your plugin support avatars in forum announcements?

**Comment by WhiteNeo** [comment]
Ok 0 impact is the way it works if disabled. Only enabled features are
loading all others are ignored.

Threads contributor yes with $avatarep takes url for seo and more.

announcements are loaded since first release of plugin and it is working.

The light version without templates addittion and guidance are on my forum
as developer version i will add it onto mybb disabling by default all
features excempt avatars.

But i will work on title tags and alt tags to make it multilang and
betterized.

I know template changes are the only problem at all so i was added
developers version onto my site for theme devs and who wish to do all by
himself but all opts are loaded so i will release both versions when i have
finished thanks for your time and i have to update some parts of code.

But how do you use thread contributor wich template because i see only is
showed in first post case but i only added to take it on meta tags for seo
on showthread template.

**Comment by Cu8eeeR** [comment]
@WhiteNeo 
here is the example on one of my boards - thread contributor is shown in the top right corner on showthread

https://www.carcassonneforum.cz/thread-287.html
![threadcontributor](https://cloud.githubusercontent.com/assets/778890/24059415/53dc5898-0b4f-11e7-8999-f9f54281b568.png)

**Comment by WhiteNeo** [comment]
Thanks for your time i have updated the plugin and i sent ew developers
version too.

Anyways formatted usernames do not have any queries due is taken from cache
and users formatted named in the mybb function, so that have not to set a
several load because is the same with or withour the mod due is the mybb
cache and plugin cache who do all the job,

And modals are taken by ajax, so it has 0 queries and loads without calling
it. Only at that moment the query is 1 only and on hover events the same
only one and if you load another and then the same again the loads are only
1 by event but if you have loaded the cache is present and all work is done
so i think all addittions are very lightweight and do not suppose overloads.

2017-03-17 13:21 GMT-06:00 Eldenroot <notifications@github.com>:

**Comment by Cu8eeeR** [comment]
@WhiteNeo - thank you for the last update - so did you include thread contributor feature?

**Comment by WhiteNeo** [comment]
It was included since first release of 2.8.x series of this mod.

You can call it on showthread template like $avatarep

I set $avatar_thread and $avatarep_thread to work with but i have not
tested yet, but should work due i have the same var addittion for SEO, but
i have to make some tests with the template you share with me.

2017-03-18 4:38 GMT-06:00 Eldenroot <notifications@github.com>:

**Comment by Cu8eeeR** [comment]
Btw - what is "Default avatar for guests" in ACP settings? MyBB v1.8.x adss automatically default avatar to users (you can change it in ACP)

**Comment by WhiteNeo** [comment]
it's an addittion only, some users would not show avatars only username for
guests, so i add it to show same as mybb if you set to on. (users
sugestion).

**Comment by WhiteNeo** [comment]
@Cu8eeeR it is ready to use the lite and major versions, so do you think i can close this or there is anything i can do ? I think Lite Version is ready so let me know. And thanks for your effort.

**Comment by Cu8eeeR** [comment]
This can be closed, thank you.

Btw - you should update the tutorial for new thread starter part :)

**Comment by WhiteNeo** [comment]
yes i will rewrite the guide i only write it quickly but i'll do is the
next on my eyes :)
