### ISSUE TITLE
Add info into tutorial - how to add thread starter into showthread template

### ISSUE THREAD

**Issue by Cu8eeeR** [WhiteNeo/lastposter-avatar-mybb18x-series#5]
Add info into tutorial - how to add thread starter into showthread template.

I need to show avatar + thread starter username into showthread template, would be nice to get a quick tutorial how to add it. Thank you!

**Comment by WhiteNeo** [comment]
I have added to the tutorial vars usefull on every template so you only
have to go to that template and add it into it as other vars.

In this case you have to go to Showthread Templates.

showthread

there you can use whenever you want the var to call avatar contributor.

{$avatarep_thread}

Use that var in the part you wish to show it and done !!

But you have to use latest file because i forgot to globalize some vars to
work with, and i have added a general js for modals or popups with another
plugins as extension and i purge the entire code to use it at a single wayi
am working on it yet, but the version in here is the working on version,
other i am experimenting problems due mybb brokes many time jquery codes
must be work, so i am searching a way to make ir easy to work fine without
errors, i am very close of that but have to test, test and test to see if i
am in the right way.

But in the guide of developers i set every template, and vars working on
each template, because as you said many users prefer to add it manually,
but in master version all changes are added automatically, so only you have
to go to template and change var at your owns, or as developers you can see
any template on list and add it in the place you wish, because is in
general for that template, maybe in other templates must works, but that
only can knowing with code inspection to see what is loaded by every hook.

2017-03-23 2:22 GMT-06:00 Eldenroot <notifications@github.com>:

**Comment by Cu8eeeR** [comment]
OK, maybe I am blind but I cannot find the template change in showthread template to shown avatar of thread author + his username (var)

**Comment by WhiteNeo** [comment]
That template uses own var

$thread['username']

but plugin provides you

$avatar['username']

and same refs for avatar format function.

but for entire customized plugin refs.

$thread_avatarep

any of those values are available. You may use at your visual reqs.
